### PR TITLE
Updates bignumber.js dependency to ^6.0

### PR DESCRIPTION
**Pull request by denlapaev**
Hi!
From bignumber.js was removed alias `sub` for `minus` method. And if you use a few dependencies which used bignumber.js and node-cbor, it has error 'NEG_ONE.sub is not a function'.

### CODE REVIEW

**Comment by hildjj** [comment]
I'm very interested in this patch.  Can you make the tests pass cleanly?

**Comment by denlapaev** [comment]
Sure, sorry about that.

I've checked all removed functions from bignumber's changelog.md.

**Comment by hildjj** [comment]
I have a few more pending changes I want to add before doing a release.  Thanks!

**Comment by hildjj** [comment]
@denlapaev can you send me a PR adding yourself to the contributors in package.json, please?

**Comment by denlapaev** [comment]
Sure.
Thank you!

**Pull request merged**
