### PR TITLE
Fix Buffer converter matcher being mangled in minimised builds

### LINKED ISSUE #164: Webpack minimize causes cbor.encode to generate a different value
Webpack minimize (https://webpack.js.org/configuration/optimization/#optimizationminimize, uses Terser) causes cbor.encode to produce a different value from when no minimize is applied.

I'm working on a minimum reproducable example for this, but essentially production build generates Uint8Array of 1661 length, and development build generates Uint8Array of 314 length.

I've pinpointed the bug to switching between `optimization.minimize: false` and `optimization.minimize: true` in my webpack config.

I'm working on a minimum reproducable example, but does this issue ring a bell? I searched github issues a bit, but there's nothing that precisely fits the bill.

I've put together the test case that fails for me on production/development builds.
```typescript

  const fromHexString = (hexString: string) =>
    new Uint8Array(
      (hexString.match(/.{1,2}/g) ?? []).map((byte) => parseInt(byte, 16))
  );

  const bufferProtected_ = Buffer.from(fromHexString("a204456b65792d310126"))
  const buffer0 = Buffer.alloc(0)
  const bufferPayload_ = Buffer.from(fromHexString("a501781e6469643a7765623a6e7a63702e636f76696431392e6865616c74682e6e7a051a61819a0a041a7450400a627663a46840636f6e7465787482782668747470733a2f2f7777772e77332e6f72672f323031382f63726564656e7469616c732f7631782a68747470733a2f2f6e7a63702e636f76696431392e6865616c74682e6e7a2f636f6e74657874732f76316776657273696f6e65312e302e306474797065827456657269666961626c6543726564656e7469616c6f5075626c6963436f766964506173737163726564656e7469616c5375626a656374a369676976656e4e616d65644a61636b6a66616d696c794e616d656753706172726f7763646f626a313936302d30342d3136075060a4f54d4e304332be33ad78b1eafa4b"))

  const SigStructure = ["Signature1", bufferProtected_, buffer0, bufferPayload_];

  const unstableResult = cbor.encode(SigStructure);
```

### PR DESCRIPTION
**Pull request by noway**
Fixes #164

- This fix might have performance implications - but it is passable for my use case.
- There are other converter matchers which might be mangled - but I only fixed Buffer since that fixes my use case

Happy to get this up to production quality/fix some other parts if i'm missing something.

### CODE REVIEW

**Comment by hildjj** [comment]
Does this work often enough to be worth it?  `isBuffer` just uses `instanceof`, and if the two Buffer implementations are different, `instanceof` won't return true.

**Comment by hildjj** [comment]
I'd be wiling to add `exports.Buffer = require('buffer').Buffer` to cbor.js, which would allow everyone to use the same (already minified) Buffer implementation.

**Comment by noway** [comment]
Hi @hildjj, thank you for taking the time to review this and also maintaining the library!

> isBuffer just uses instanceof, and if the two Buffer implementations are different, instanceof won't return true.

I'm not sure I fully get this argument, I might be missing something.

`Buffer` implementation is part of the javascript bundle I vendor: https://unpkg.com/@vaxxnz/nzcp@0.1.5/dist/esbuild/browser.js. 

I don't expose any `Buffer` interfaces, so it's guaranteed I always originate the usage of `Buffer` inside the library. While `Buffer.name` gets mangled and can differ, `Buffer` instance itself is the same inside the bundle.

If I were to expose some `Buffer` interfaces, I could run `Buffer.from()` on them to make sure I'm using the right `Buffer` implementation. It's not ideal, but workable.

What's a scenario when this would break down? 

Cheers.

**Comment by noway** [comment]
The workaround from https://github.com/hildjj/node-cbor/issues/164#issuecomment-994020193 solves this issue for me, so I going to close this pull request.

**Pull request closed without merging**
