### PR TITLE
Improved performance after fix for Nodejs 10 Buffer deprecations

### PR DESCRIPTION
**Pull request by BurtHarris**
The deprecation fixes can be optimized by using `Buffer.allocUnsafe()` instead of `Buffer.alloc()`.

Updates package.json required Node.js version to 5.10.0 (as that's needed for Buffer.alloc() etc.

Also adds a minor test case I used to convince myself that #74 wasn't really a problem.

### CODE REVIEW

**Comment by hildjj** [comment]
I'll take this PR after Node v10 has made it a hair further through the ecosystem and I turn off v4 support.  A couple of weeks at most.

**Comment by BurtHarris** [comment]
Cool, thanks.

**Comment by hildjj** [comment]
Trying the "rebase and merge" feature; this needs to be behind 3e6371e.

**Comment by hildjj** [comment]
@BurtHarris I just realized you're not on the contributors list.  Can you send me another PR adding yourself to `package.json` please?

**Pull request merged**
